version: "3.6"
services:
  fb-api-service:
    image: fb-api-img:v1
    build: .
    restart: on-failure
    container_name: ${PROJECT_ID}-container
    ports:
      - "3002:3002"


networks:
  default:
    external:
      name: fb-network

