apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: fb-api
build:
  artifacts:
  - image: vijayakumarpsg587/fb-api-img
    context: deployments/docker
deploy:
  kubectl:
    manifests:
    - deployments/kubernetes/deployment.yaml
    - deployments/kubernetes/ingress.yaml
    - deployments/kubernetes/secrets.yaml
    - deployments/kubernetes/service.yaml
