version: 2.1

jobs:
  build_app:
    description: Building image with custom docker
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: alpine:3.12.0
    
    steps:
      - checkout
      - setup_remote_docker
#          docker_layer_caching: true - Not enabled i
#
      - run:
          name: INstall pre-req
          command: |
            apk add --no-cache ca-certificates
            mkdir /usr/share/ca-certificates/extra
            update-ca-certificates
            
      - run:
          name: Install Docker client
          command: |
            set -x
            apk add --no-cache docker-cli python3 py3-pip
            apk add --no-cache --virtual .docker-compose-deps python3-dev libffi-dev openssl-dev gcc libc-dev make 
            docker version
            docker ps
            pip3 install docker-compose
            apk del .docker-compose-deps
            docker-compose version
            

      - run:
          name: Build docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
            docker version
            docker-compose version
            docker-compose build --force-rm --no-cache
#
      - run:
          name: Push the img to a repo
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
            docker tag ${PROJECT_ID}:${TAG} ${DOCKER_HUB_CONTEXT}/${PROJECT_ID}:${TAG}
            docker push ${DOCKER_HUB_CONTEXT}/${PROJECT_ID}:${TAG}
workflows:
  version: 2
  fb-api-docker-workflow:
    jobs:
      - build_app



