version: 2.1
executors:
  docker_node_executor:
    docker:
      image: node:13-alpine3.10
  machine_executor:
    machine: true
jobs:
  build-app:
    description: Building image with custom docker
    executor: docker_node_executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Test the source
          command: |
            echo "test"
      - run:
          name: Build docker image
          command: |
            TAG:v.$CIRCLE_SHA1
            docker build -t $DOCKER_HUB_CONTEXT/$PROJECT_ID:$TAG .
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
            docker push $DOCKER_HUB_CONTEXT/$PROJECT_ID:$TAG
  run-app:
    description: Run the built image
    run:
      name: Executing the run commands
      command: |
        docker run -d --name ${PROJECT_ID}-container -p 3002:3002 ${DOCKER_HUB_CONTEXT}/${PROJECT_ID}:$TAG
workflows:
  build-app:
  run-app:
    requires: build-app



