version: 2.0
jobs:
  build_app:
    description: Building image with custom docker
    machine: true
    steps:
      - checkout
#          docker_layer_caching: true
#      - run:
#          name: Test the source
#          command: |
#            echo "test"
      - run:
          name: Build docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
            echo ${DOCKER_HUB_CONTEXT}/${PROJECT_ID}:${TAG}
            docker version
            docker build -t ${DOCKER_HUB_CONTEXT}/${PROJECT_ID}:v1 -f ./../deployments/docker/Dockerfile .
            docker push $DOCKER_HUB_CONTEXT/$PROJECT_ID:$TAG
      
  run_app:
    description: Run the built image
    docker:
      - image: docker:19.03
    steps:
      - run:
          name: Executing the run commands
          command: |
            docker run -d --name ${PROJECT_ID}-container -p 3002:3002 ${DOCKER_HUB_CONTEXT}/${PROJECT_ID}:$TAG
workflows:
  version: 2
  fb-api-docker-workflow:
    jobs:
      - build_app
      - run_app:
          requires:
            - build_app



